[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.96"

[workspace]
members = [
    "src/DyLib/Primitives/Plane",
    "src/DyLib/Primitives/Sphere",
]